
project_id = "vygluorjwehcdigzxbaa"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[functions]
[functions.apiframe-video-create-task]
verify_jwt = false
