
project_id = "sxcdfhomogjtjdtoolbg"

[functions.apiframe-generate-audio]
verify_jwt = true

[functions.increment-post-view]
verify_jwt = true

[functions.user-tokens]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.admin-update-tokens]
verify_jwt = true

[functions.newsletter-media-storage]
verify_jwt = true
