
project_id = "vygluorjwehcdigzxbaa"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[realtime]
enabled = true
port = 54327

[functions]
[functions.apiframe-check-status]
verify_jwt = true
[functions.apiframe-generate-audio]
verify_jwt = true
[functions.apiframe-generate-image]
verify_jwt = true
[functions.apiframe-generate-video]
verify_jwt = true
[functions.apiframe-task-cancel]
verify_jwt = true
[functions.user-tokens]
verify_jwt = true
[functions.openrouter-chat]
verify_jwt = true
[functions.openrouter-stream]
verify_jwt = true
[functions.openrouter-models]
verify_jwt = true
