
project_id = ""

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = true
ip_address = "0.0.0.0"
port = 54323

[studio]
enabled = true
port = 54324
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://127.0.0.1:3000", "http://localhost:5173", "https://lovable-ai.vercel.app"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false

[auth.sms]
enable_signup = true
enable_confirmations = true

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
additional_redirect_urls = [""]

[auth.external.google]
enabled = false
client_id = ""
secret = ""
admin_email = ""
additional_redirect_urls = [""]

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
additional_redirect_urls = [""]

[auth.external.github]
enabled = false
client_id = ""
secret = ""
additional_redirect_urls = [""]

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
url = ""
additional_redirect_urls = [""]

[analytics]
enabled = false
backend = "postgres"
detailed_errors = false

[experimental.functions.ai-chat]
port = 54327
verify_jwt = true
timeout_seconds = 600

[experimental.functions.media-storage]
port = 54328
verify_jwt = true
timeout_seconds = 300
