
project_id = "lovable"

[functions.openrouter-stream]
verify_jwt = true

[functions.openrouter-chat]
verify_jwt = true

[functions.openrouter-models]
verify_jwt = true

[functions.apiframe-image-generate]
verify_jwt = true
