
project_id = "vygluorjwehcdigzxbaa"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
port = 54327
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://localhost:3000"]
autoconfirm = true
disable_signup = false

[storage]
port = 54328

[vector]
port = 54329

[functions.ai-chat]
verify_jwt = true

[functions.google-oauth-callback]
verify_jwt = false

[functions.google-token-refresh]
verify_jwt = true

[functions.google-verify-permissions]
verify_jwt = true

[functions.media-storage]
verify_jwt = true

[functions.memory-extractor]
verify_jwt = true

[functions.user-tokens]
verify_jwt = true

[functions.google_calendar_createEvent]
verify_jwt = true
path = "google/calendar/createEvent"

[functions.google_sheets_write]
verify_jwt = true
path = "google/sheets/write"

[functions.google_docs_create]
verify_jwt = true
path = "google/docs/create"
