
# project configuration in supabase
project_id = "vygluorjwehcdigzxbaa"

[api]
enabled = true
url = "https://vygluorjwehcdigzxbaa.supabase.co"

[db]
shadow = false

[functions]
[functions.apiframe-generate-image]
verify_jwt = true

[functions.apiframe-generate-video]
verify_jwt = true

[functions.apiframe-media-webhook]
verify_jwt = false

[functions.apiframe-task-status]
verify_jwt = true
