
# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "inventu-ai"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "extensions"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 54323

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "https://super-intellect-companion-ai.lovable.app"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = [
  "https://super-intellect-companion-ai.lovable.app",
  "https://super-intellect-companion-ai.lovable.app/auth",
  "https://super-intellect-companion-ai.lovable.app/google-integrations"
]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Configure Edge Functions
[functions]
# Port to use for Edge Functions emulator.
port = 54321
serve_port = 54900

# Specific function configurations
[functions.google-oauth-callback]
verify_jwt = false

[functions.google-token-refresh]
verify_jwt = false

[functions.google-verify-permissions]
verify_jwt = false

[functions.google-calendar-create-event]
verify_jwt = false

[functions.google-calendar-list-events]
verify_jwt = false

[functions.google-sheets-create]
verify_jwt = false

[functions.google-sheets-read]
verify_jwt = false

[functions.google-sheets-update]
verify_jwt = false

[functions.google-docs-create]
verify_jwt = false

[functions.google-docs-update]
verify_jwt = false

[functions.google-drive-upload]
verify_jwt = false

[functions.google-drive-create-folder]
verify_jwt = false

[functions.google-gmail-send]
verify_jwt = false
