
project_id = "lovable"

[functions.apiframe-video-create-task]

[functions.apiframe-task-status]

[functions.apiframe-task-cancel]

[functions.apiframe-media-webhook]
verify_jwt = false

[functions.piapi-image-create-task]

[functions.piapi-task-status]

[functions.ai-chat]

[functions.apiframe-suno-create-task]

[functions.get-supabase-url]
