
project_id = "vygluorjwehcdigzxbaa"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = false
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"

[realtime]
enabled = true

[functions]
[functions.admin-update-tokens]
verify_jwt = true
[functions.apiframe-generate-audio]
verify_jwt = false
[functions.apiframe-generate-image]
verify_jwt = false
[functions.apiframe-check-status]
verify_jwt = false
[functions.apiframe-task-cancel]
verify_jwt = false
[functions.apiframe-image]
verify_jwt = false
[functions.apiframe-task-status]
verify_jwt = false
