// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxcdfhomogjtjdtoolbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4Y2RmaG9tb2dqdGpkdG9vbGJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMjMwMjgsImV4cCI6MjA2MTU5OTAyOH0.Rz4efW5gByMiVlyT165kTj8P8Sw9W7wS70Uf9QsieKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);