
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Since we can't modify the types.ts file, we'll define a basic Database interface here
interface Database {
  public: {
    Tables: {
      newsletter_posts: {
        Row: {
          id: string;
          title: string;
          content: string;
          user_id: string;
          published_at: string | null;
          media_url: string | null;
          media_type: 'none' | 'image' | 'video' | 'audio' | null;
          view_count: number | null;
          like_count: number | null;
          share_count: number | null;
          created_at: string;
          updated_at: string;
          is_published?: boolean;
          author_id?: string;
        };
      };
      post_likes: {
        Row: {
          id: string;
          user_id: string;
          post_id: string;
          created_at: string;
        };
      };
      post_comments: {
        Row: {
          id: string;
          post_id: string;
          user_id: string;
          content: string;
          created_at: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          username: string | null;
          avatar_url: string | null;
          is_admin: boolean | null;
        };
      };
      user_google_tokens: {
        Row: {
          id: string;
          user_id: string;
          access_token: string;
          refresh_token: string;
          expires_at: number;
          created_at: string;
          updated_at: string;
        };
      };
      apiframe_tasks: {
        Row: {
          id: string;
          task_id: string;
          user_id: string | null;
          prompt: string | null;
          model: string;
          media_type: string;
          media_url: string | null;
          status: string;
          params: any;
          percentage: number | null;
          error: string | null;
          created_at: string;
          updated_at: string;
        };
      };
      media_analytics: {
        Row: {
          id: string;
          event_type: string;
          media_type: string;
          model_id: string;
          user_id: string | null;
          created_at: string;
        };
      };
      media_ready_events: {
        Row: {
          id: string;
          task_id: string;
          media_url: string;
          media_type: string;
          model: string;
          prompt: string | null;
          created_at: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          title: string;
          user_id: string;
          updated_at: string;
          created_at: string;
        };
      };
      messages: {
        Row: {
          id: string;
          content: string;
          sender: string;
          timestamp: string;
          conversation_id: string;
          model?: string;
          mode?: string;
          files?: string[];
          media_url?: string | null;
        };
      };
      piapi_tasks: {
        Row: {
          id: string;
          task_id: string;
          user_id: string | null;
          prompt: string | null;
          model: string;
          media_type: string;
          media_url: string | null;
          status: string;
          params: any;
          percentage: number | null;
          error: string | null;
          created_at: string;
          updated_at: string;
        };
      };
      user_memory: {
        Row: {
          id: string;
          user_id: string;
          key_name: string;
          value: string | null;
          source: string;
          title: string | null;
          created_at: string;
          updated_at: string;
        };
      };
    };
  };
}

const SUPABASE_URL = "https://sxcdfhomogjtjdtoolbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4Y2RmaG9tb2dqdGpkdG9vbGJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMjMwMjgsImV4cCI6MjA2MTU5OTAyOH0.Rz4efW5gByMiVlyT165kTj8P8Sw9W7wS70Uf9QsieKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
